version: "3"
services: 
    db: 
        image: postgres
        environment: 
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: tEst@1!3*
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports: 
            - '5432:5432'
    
    backend:
        build: .
        restart: always
        image: node:17-alpine3.14
        container_name: backend
        env_file: .env
        ports:
            - 3009:3009
        volumes: 
            - .:/app
        depends_on: 
            - db